<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_penjualan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detail_penjualan_model');
    } 

    /*
     * Listing of detail_penjualan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('detail_penjualan/index?');
        $config['total_rows'] = $this->Detail_penjualan_model->get_all_detail_penjualan_count();
        $this->pagination->initialize($config);

        $data['detail_penjualan'] = $this->Detail_penjualan_model->get_all_detail_penjualan($params);
        
        $data['_view'] = 'detail_penjualan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new detail_penjualan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('detail_penjualan_nota','Detail Penjualan Nota','required');
		$this->form_validation->set_rules('detail_produk_id','Detail Produk Id','required');
		$this->form_validation->set_rules('detail_jumlah_beli','Detail Jumlah Beli','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'detail_penjualan_nota' => $this->input->post('detail_penjualan_nota'),
				'detail_produk_id' => $this->input->post('detail_produk_id'),
				'detail_jumlah_beli' => $this->input->post('detail_jumlah_beli'),
            );
            
            $detail_penjualan_id = $this->Detail_penjualan_model->add_detail_penjualan($params);
            redirect('detail_penjualan/index');
        }
        else
        {
			$this->load->model('Penjualan_model');
			$data['all_penjualan'] = $this->Penjualan_model->get_all_penjualan();

			$this->load->model('Produk_model');
			$data['all_produk'] = $this->Produk_model->get_all_produk();
            
            $data['_view'] = 'detail_penjualan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a detail_penjualan
     */
    function edit($detail_id)
    {   
        // check if the detail_penjualan exists before trying to edit it
        $data['detail_penjualan'] = $this->Detail_penjualan_model->get_detail_penjualan($detail_id);
        
        if(isset($data['detail_penjualan']['detail_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('detail_penjualan_nota','Detail Penjualan Nota','required');
			$this->form_validation->set_rules('detail_produk_id','Detail Produk Id','required');
			$this->form_validation->set_rules('detail_jumlah_beli','Detail Jumlah Beli','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'detail_penjualan_nota' => $this->input->post('detail_penjualan_nota'),
					'detail_produk_id' => $this->input->post('detail_produk_id'),
					'detail_jumlah_beli' => $this->input->post('detail_jumlah_beli'),
                );

                $this->Detail_penjualan_model->update_detail_penjualan($detail_id,$params);            
                redirect('detail_penjualan/index');
            }
            else
            {
				$this->load->model('Penjualan_model');
				$data['all_penjualan'] = $this->Penjualan_model->get_all_penjualan();

				$this->load->model('Produk_model');
				$data['all_produk'] = $this->Produk_model->get_all_produk();

                $data['_view'] = 'detail_penjualan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The detail_penjualan you are trying to edit does not exist.');
    } 

    /*
     * Deleting detail_penjualan
     */
    function remove($detail_id)
    {
        $detail_penjualan = $this->Detail_penjualan_model->get_detail_penjualan($detail_id);

        // check if the detail_penjualan exists before trying to delete it
        if(isset($detail_penjualan['detail_id']))
        {
            $this->Detail_penjualan_model->delete_detail_penjualan($detail_id);
            redirect('detail_penjualan/index');
        }
        else
            show_error('The detail_penjualan you are trying to delete does not exist.');
    }
    
}
