<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kasir extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kasir_model');
    } 

    /*
     * Listing of kasir
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('kasir/index?');
        $config['total_rows'] = $this->Kasir_model->get_all_kasir_count();
        $this->pagination->initialize($config);

        $data['kasir'] = $this->Kasir_model->get_all_kasir($params);
        
        $data['_view'] = 'kasir/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kasir
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('kasir_nama','Kasir Nama','required');
		$this->form_validation->set_rules('kasir_email','Kasir Email','required|valid_email');
		$this->form_validation->set_rules('kasir_telepon','Kasir Telepon','required|numeric');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'kasir_nama' => $this->input->post('kasir_nama'),
				'kasir_email' => $this->input->post('kasir_email'),
				'kasir_telepon' => $this->input->post('kasir_telepon'),
            );
            
            $kasir_id = $this->Kasir_model->add_kasir($params);
            redirect('kasir/index');
        }
        else
        {            
            $data['_view'] = 'kasir/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kasir
     */
    function edit($kasir_id)
    {   
        // check if the kasir exists before trying to edit it
        $data['kasir'] = $this->Kasir_model->get_kasir($kasir_id);
        
        if(isset($data['kasir']['kasir_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('kasir_nama','Kasir Nama','required');
			$this->form_validation->set_rules('kasir_email','Kasir Email','required|valid_email');
			$this->form_validation->set_rules('kasir_telepon','Kasir Telepon','required|numeric');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'kasir_nama' => $this->input->post('kasir_nama'),
					'kasir_email' => $this->input->post('kasir_email'),
					'kasir_telepon' => $this->input->post('kasir_telepon'),
                );

                $this->Kasir_model->update_kasir($kasir_id,$params);            
                redirect('kasir/index');
            }
            else
            {
                $data['_view'] = 'kasir/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kasir you are trying to edit does not exist.');
    } 

    /*
     * Deleting kasir
     */
    function remove($kasir_id)
    {
        $kasir = $this->Kasir_model->get_kasir($kasir_id);

        // check if the kasir exists before trying to delete it
        if(isset($kasir['kasir_id']))
        {
            $this->Kasir_model->delete_kasir($kasir_id);
            redirect('kasir/index');
        }
        else
            show_error('The kasir you are trying to delete does not exist.');
    }
    
}
