<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Produk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Produk_model');
    } 

    /*
     * Listing of produk
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('produk/index?');
        $config['total_rows'] = $this->Produk_model->get_all_produk_count();
        $this->pagination->initialize($config);

        $data['produk'] = $this->Produk_model->get_all_produk($params);
        
        $data['_view'] = 'produk/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new produk
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('produk_nama','Produk Nama','required');
		$this->form_validation->set_rules('produk_harga','Produk Harga','required|numeric');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'produk_nama' => $this->input->post('produk_nama'),
				'produk_harga' => $this->input->post('produk_harga'),
            );
            
            $produk_id = $this->Produk_model->add_produk($params);
            redirect('produk/index');
        }
        else
        {            
            $data['_view'] = 'produk/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a produk
     */
    function edit($produk_id)
    {   
        // check if the produk exists before trying to edit it
        $data['produk'] = $this->Produk_model->get_produk($produk_id);
        
        if(isset($data['produk']['produk_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('produk_nama','Produk Nama','required');
			$this->form_validation->set_rules('produk_harga','Produk Harga','required|numeric');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'produk_nama' => $this->input->post('produk_nama'),
					'produk_harga' => $this->input->post('produk_harga'),
                );

                $this->Produk_model->update_produk($produk_id,$params);            
                redirect('produk/index');
            }
            else
            {
                $data['_view'] = 'produk/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The produk you are trying to edit does not exist.');
    } 

    /*
     * Deleting produk
     */
    function remove($produk_id)
    {
        $produk = $this->Produk_model->get_produk($produk_id);

        // check if the produk exists before trying to delete it
        if(isset($produk['produk_id']))
        {
            $this->Produk_model->delete_produk($produk_id);
            redirect('produk/index');
        }
        else
            show_error('The produk you are trying to delete does not exist.');
    }
    
}
