<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_penjualan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detail_penjualan by detail_id
     */
    function get_detail_penjualan($detail_id)
    {
        return $this->db->get_where('detail_penjualan',array('detail_id'=>$detail_id))->row_array();
    }
    
    /*
     * Get all detail_penjualan count
     */
    function get_all_detail_penjualan_count()
    {
        $this->db->from('detail_penjualan');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all detail_penjualan
     */
    function get_all_detail_penjualan($params = array())
    {
        $this->db->order_by('detail_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('detail_penjualan')->result_array();
    }
        
    /*
     * function to add new detail_penjualan
     */
    function add_detail_penjualan($params)
    {
        $this->db->insert('detail_penjualan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detail_penjualan
     */
    function update_detail_penjualan($detail_id,$params)
    {
        $this->db->where('detail_id',$detail_id);
        return $this->db->update('detail_penjualan',$params);
    }
    
    /*
     * function to delete detail_penjualan
     */
    function delete_detail_penjualan($detail_id)
    {
        return $this->db->delete('detail_penjualan',array('detail_id'=>$detail_id));
    }
}
