<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kasir_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kasir by kasir_id
     */
    function get_kasir($kasir_id)
    {
        return $this->db->get_where('kasir',array('kasir_id'=>$kasir_id))->row_array();
    }
    
    /*
     * Get all kasir count
     */
    function get_all_kasir_count()
    {
        $this->db->from('kasir');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all kasir
     */
    function get_all_kasir($params = array())
    {
        $this->db->order_by('kasir_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('kasir')->result_array();
    }
        
    /*
     * function to add new kasir
     */
    function add_kasir($params)
    {
        $this->db->insert('kasir',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kasir
     */
    function update_kasir($kasir_id,$params)
    {
        $this->db->where('kasir_id',$kasir_id);
        return $this->db->update('kasir',$params);
    }
    
    /*
     * function to delete kasir
     */
    function delete_kasir($kasir_id)
    {
        return $this->db->delete('kasir',array('kasir_id'=>$kasir_id));
    }
}
