<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Penjualan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get penjualan by penjualan_id
     */
    function get_penjualan($penjualan_id)
    {
        return $this->db->get_where('penjualan',array('penjualan_id'=>$penjualan_id))->row_array();
    }
    
    /*
     * Get all penjualan count
     */
    function get_all_penjualan_count()
    {
        $this->db->from('penjualan');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all penjualan
     */
    function get_all_penjualan($params = array())
    {
        $this->db->order_by('penjualan_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('penjualan')->result_array();
    }
        
    /*
     * function to add new penjualan
     */
    function add_penjualan($params)
    {
        $this->db->insert('penjualan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update penjualan
     */
    function update_penjualan($penjualan_id,$params)
    {
        $this->db->where('penjualan_id',$penjualan_id);
        return $this->db->update('penjualan',$params);
    }
    
    /*
     * function to delete penjualan
     */
    function delete_penjualan($penjualan_id)
    {
        return $this->db->delete('penjualan',array('penjualan_id'=>$penjualan_id));
    }
}
